settings:
  tg:
    chat-id: # сюда желательно указывать чаты, узнать ID чата можно тут: https://api.telegram.org/botToken/getUpdates
      - ""
    token: ""
    enable: false
  vk:
    chat-id:
      - ""
    token: ""
    enable: true
  ds:
    url: ""
    enable: false
    color:
      red: 15548997
      green: 5763719
      yellow: 16776960

messages:
  attempt: "попытка"
  tryings: "попытки"
  attempts: "попыток"

  captured-player:
    - "Был пойман игрок с админ-правами!"
    - ""
    - "Ник: %player%"
    - "IP: %ip%"
  success-auth:
    - "Администратор успешно авторизовался в систему!"
    - ""
    - "Ник: %player%"
    - "IP: %ip%"
  logout-player:
    - "Администратор завершил сессию!"
    - ""
    - "Ник: %player%"
    - "IP: %ip%"
  enter-password:
    - "Администратор ввёл пароль!"
    - ""
    - "Ник: %player%"
    - "Пароль: %player%" # можно убрать, если мешает :)
    - "IP: %ip%"
  fail-auth:
    - "Администратор ввёл неправильно пароль"
    - ""
    - "Ник: %player%"
    - "%attempts%" # отдаст 1 попытка или 2 попытки
    - "IP: %ip%"
