settings:
  tg:
    chat-id:
      - ""
    token: ""
    enable: false
  vk:
    chat-id:
      - ""
    token: ""
    enable: true
  ds:
    url: ""
    enable: false
    color:
      red: 15548997
      green: 5763719
      yellow: 16776960

messages:
  attempts:
    - попыт
    - ка
    - ки
    - ок # thx dotmix

  captured-player:
    - "Был пойман игрок с админ-правами!"
    - ""
    - "Ник: %player%"
    - "IP: %ip%"
  success-auth:
    - "Администратор успешно авторизовался в систему!"
    - ""
    - "Ник: %player%"
    - "IP: %ip%"
  logout-player:
    - "Администратор завершил сессию!"
    - ""
    - "Ник: %player%"
    - "IP: %ip%"
  enter-password:
    - "Администратор ввёл пароль!"
    - ""
    - "Ник: %player%"
    - "Пароль: %password%" # можно убрать, если мешает :)
    - "IP: %ip%"
  fail-auth:
    - "Администратор ввёл неправильно пароль"
    - ""
    - "Ник: %player%"
    - "%attempts%" # отдаст 1 попытка или 2 попытки
    - "IP: %ip%"
